packages:
  - apps/*
  - packages/*

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: 8.5.17
  sharp: 0.35.0
  uuid: 11.1.1

minimumReleaseAgeExclude:
  - "@better-auth/core@1.6.24"
  - "@better-auth/drizzle-adapter@1.6.24"
  - "@better-auth/kysely-adapter@1.6.24"
  - "@better-auth/memory-adapter@1.6.24"
  - "@better-auth/mongo-adapter@1.6.24"
  - "@better-auth/prisma-adapter@1.6.24"
  - "@better-auth/telemetry@1.6.24"
  - "@turbo/darwin-64@2.10.6"
  - "@turbo/darwin-arm64@2.10.6"
  - "@turbo/linux-64@2.10.6"
  - "@turbo/linux-arm64@2.10.6"
  - "@turbo/windows-64@2.10.6"
  - "@turbo/windows-arm64@2.10.6"
  - better-auth@1.6.24
  - turbo@2.10.6
  - "@aws-sdk/client-s3@3.1093.0"
  - "@aws-sdk/s3-request-presigner@3.1093.0"
